In [30]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

dados_bruto = pd.read_csv("/content/students_mental_health_survey.csv")
dados_bruto.head()

Age            Course  Gender  CGPA  Stress_Level  Depression_Score  \
0   25            Others    Male  3.56             3                 3   
1   24       Engineering  Female  2.44             0                 3   
2   19          Business  Female  3.74             4                 0   
3   19  Computer Science    Male  3.65             2                 1   
4   18          Business    Male  3.40             3                 3   

   Anxiety_Score Sleep_Quality Physical_Activity Diet_Quality Social_Support  \
0              2          Good          Moderate         Good       Moderate   
1              0       Average               Low      Average            Low   
2              3          Good               Low      Average       Moderate   
3              0       Average               Low      Average       Moderate   
4              4          Good               Low      Average           High   

  Relationship_Status Substance_Use Counseling_Service_Use Family_History  \
0             Married         Never                  Never             No   
1              Single  Occasionally           Occasionally             No   
2   In a Relationship         Never           Occasionally             No   
3              Single           NaN                  Never             No   
4             Married         Never                  Never             No   

  Chronic_Illness  Financial_Stress Extracurricular_Involvement  \
0              No                 2                    Moderate   
1              No                 3                         Low   
2              No                 4                        High   
3              No                 4                    Moderate   
4             Yes                 0                        High   

   Semester_Credit_Load Residence_Type  
0                    17      On-Campus  
1                    27      On-Campus  
2                    15      On-Campus  
3                    20     Off-Campus  
4                    23      On-Campus

##**Limpando DataSet**


In [31]:
dados = dados_bruto.dropna()
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6995 entries, 0 to 7020
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Age                          6995 non-null   int64  
 1   Course                       6995 non-null   object 
 2   Gender                       6995 non-null   object 
 3   CGPA                         6995 non-null   float64
 4   Stress_Level                 6995 non-null   int64  
 5   Depression_Score             6995 non-null   int64  
 6   Anxiety_Score                6995 non-null   int64  
 7   Sleep_Quality                6995 non-null   object 
 8   Physical_Activity            6995 non-null   object 
 9   Diet_Quality                 6995 non-null   object 
 10  Social_Support               6995 non-null   object 
 11  Relationship_Status          6995 non-null   object 
 12  Substance_Use                6995 non-null   object 
 13  Counseling_Service

In [60]:
stress = "Stress_Level"
depre = "Depression_Score"
ansiedade = "Anxiety_Score"
social = "Social_Support"
sono = "Sleep_Quality"
diet = "Diet_Quality"
relac = "Relationship_Status"
subs = "Substance_Use"
creditos = "Semester_Credit_Load"
curso ="Course"
casa = "Residence_Type"
aconselhamento = "Counseling_Service_Use"
atvdd_fisica = 'Physical_Activity'

In [33]:
cont = 2

for x in dados[sono].unique():
  dados[sono] = dados[sono].replace(x, cont)
  cont -= 1

dados[sono].unique()

<ipython-input-33-1f0ce5fe5c49>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados[sono] = dados[sono].replace(x, cont)


array([2, 1, 0])

In [35]:
cont = 0

for x in dados[aconselhamento].unique():
  dados[aconselhamento] = dados[aconselhamento].replace(x, cont)
  cont += 1

dados[aconselhamento].unique()

<ipython-input-35-6f4ffb3979b2>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados[aconselhamento] = dados[aconselhamento].replace(x, cont)


array([0, 1, 2])

In [66]:
cont = 0

for x in ['Low','Moderate','High']:
  dados[atvdd_fisica] = dados[atvdd_fisica].replace(x, cont)
  cont += 1

dados[atvdd_fisica].unique()

<ipython-input-66-731b7d36509f>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados[atvdd_fisica] = dados[atvdd_fisica].replace(x, cont)


array([1, 0, 2])

In [67]:
dados.head()

Age       Course  Gender  CGPA  Stress_Level  Depression_Score  \
0   25       Others    Male  3.56             3                 3   
1   24  Engineering  Female  2.44             0                 3   
2   19     Business  Female  3.74             4                 0   
4   18     Business    Male  3.40             3                 3   
5   21      Medical  Female  3.35             2                 4   

   Anxiety_Score  Sleep_Quality  Physical_Activity Diet_Quality  \
0              2              2                  1         Good   
1              0              1                  0      Average   
2              3              2                  0      Average   
4              4              2                  0      Average   
5              3              2                  1         Good   

  Social_Support Relationship_Status Substance_Use  Counseling_Service_Use  \
0       Moderate             Married         Never                       0   
1            Low              Single  Occasionally                       1   
2       Moderate   In a Relationship         Never                       1   
4           High             Married         Never                       0   
5           High              Single         Never                       0   

  Family_History Chronic_Illness  Financial_Stress  \
0             No              No                 2   
1             No              No                 3   
2             No              No                 4   
4             No             Yes                 0   
5             No              No                 5   

  Extracurricular_Involvement  Semester_Credit_Load Residence_Type  
0                    Moderate                    17      On-Campus  
1                         Low                    27      On-Campus  
2                        High                    15      On-Campus  
4                        High                    23      On-Campus  
5                    Moderate                    19     Off-Campus

##**Respondendo Perguntas**

1- Qualidade de Sono e Nivel de estresse são inversamente proporcionais ??

In [87]:
for c in dados[curso].unique():
  print(f'Para o curso {c}: {dados[(dados[curso] == c)][[stress, sono]].corr()[sono][0]:.3f}')

# Nao

Para o curso Others: -0.065
Para o curso Engineering: 0.008
Para o curso Business: 0.069
Para o curso Medical: -0.007
Para o curso Law: 0.005
Para o curso Computer Science: 0.006


2- Há uma diferença nos niveis de ansiedade entre alunos que usam serviços de aconselhamento e alunos que não usam ??

In [59]:
for c in dados[curso].unique():
  print(f'Para o curso {c}:')
  print(f'Media dos Niveis de ansiedade de alunos que não usam aconselhamento: {dados[(dados[curso] == c) & (dados[aconselhamento] == 0)][ansiedade].mean():.3f}')
  print(f'Media dos Niveis de ansiedade de alunos que usam aconselhamento fraco: {dados[(dados[curso] == c) & (dados[aconselhamento] == 1)][ansiedade].mean():.3f}')
  print(f'Media dos Niveis de ansiedade de alunos que usam aconselhamento forte: {dados[(dados[curso] == c) & (dados[aconselhamento] == 2)][ansiedade].mean():.3f}')


  print()

print(f'Desvio padrao ansiedade: {np.std([dados[ansiedade]])}')
print(f'Desvio padrao aconselhamento: {np.std([dados[aconselhamento]])}')

# Não necessariamente


Para o curso Others:
Media dos Niveis de ansiedade de alunos que não usam aconselhamento: 2.047
Media dos Niveis de ansiedade de alunos que usam aconselhamento fraco: 2.171
Media dos Niveis de ansiedade de alunos que usam aconselhamento forte: 2.342

Para o curso Engineering:
Media dos Niveis de ansiedade de alunos que não usam aconselhamento: 2.062
Media dos Niveis de ansiedade de alunos que usam aconselhamento fraco: 2.155
Media dos Niveis de ansiedade de alunos que usam aconselhamento forte: 1.904

Para o curso Business:
Media dos Niveis de ansiedade de alunos que não usam aconselhamento: 2.021
Media dos Niveis de ansiedade de alunos que usam aconselhamento fraco: 2.093
Media dos Niveis de ansiedade de alunos que usam aconselhamento forte: 1.927

Para o curso Medical:
Media dos Niveis de ansiedade de alunos que não usam aconselhamento: 2.085
Media dos Niveis de ansiedade de alunos que usam aconselhamento fraco: 2.116
Media dos Niveis de ansiedade de alunos que usam aconselhamento fo

3- Qual é o impacto das atividades físicas na depressão dos estudantes ??

In [72]:
for c in dados[curso].unique():
  print(f'Para o curso {c}:')
  print(f'Media dos Niveis de Depressao de alunos que não Fazem exercicios fisicos: {dados[(dados[curso] == c) & (dados[atvdd_fisica] == 0)][depre].mean():.3f}')
  print(f'Media dos Niveis de Depressao de alunos que fazem alguns exercicios fisicos: {dados[(dados[curso] == c) & (dados[atvdd_fisica] == 1)][depre].mean():.3f}')
  print(f'Media dos Niveis de Depressao de alunos que fazem muitos exercicios fisicos: {dados[(dados[curso] == c) & (dados[atvdd_fisica] == 2)][depre].mean():.3f}')


  print()

print(f'Desvio padrao Atividades Fisicas: {np.std([dados[atvdd_fisica]])}')
print(f'Desvio padrao Depressao: {np.std([dados[depre]])}')



Para o curso Others:
Media dos Niveis de Depressao de alunos que não Fazem exercicios fisicos: 2.027
Media dos Niveis de Depressao de alunos que fazem alguns exercicios fisicos: 2.053
Media dos Niveis de Depressao de alunos que fazem muitos exercicios fisicos: 2.213

Para o curso Engineering:
Media dos Niveis de Depressao de alunos que não Fazem exercicios fisicos: 2.022
Media dos Niveis de Depressao de alunos que fazem alguns exercicios fisicos: 2.128
Media dos Niveis de Depressao de alunos que fazem muitos exercicios fisicos: 2.075

Para o curso Business:
Media dos Niveis de Depressao de alunos que não Fazem exercicios fisicos: 2.276
Media dos Niveis de Depressao de alunos que fazem alguns exercicios fisicos: 2.006
Media dos Niveis de Depressao de alunos que fazem muitos exercicios fisicos: 2.090

Para o curso Medical:
Media dos Niveis de Depressao de alunos que não Fazem exercicios fisicos: 2.005
Media dos Niveis de Depressao de alunos que fazem alguns exercicios fisicos: 2.072
Medi